/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package meman;

import java.util.ArrayList;
import java.nio.file.*;

/**
 *
 * @author JOSH
 */
public class Main extends javax.swing.JFrame {
 
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        searchingProgressBar.setMinimum(0);
        searchingProgressBar.setStringPainted(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        titleList = new javax.swing.JList();
        searchTextBox = new javax.swing.JTextField();
        directoryToSearchTextBox = new javax.swing.JTextField();
        lab1 = new javax.swing.JLabel();
        searchingProgressBar = new javax.swing.JProgressBar();
        reSearchButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sizeList = new javax.swing.JList();
        lab4 = new javax.swing.JLabel();
        numMoviesLab = new javax.swing.JLabel();
        lab3 = new javax.swing.JLabel();
        totalSizeLab = new javax.swing.JLabel();
        lab2 = new javax.swing.JLabel();
        numMoviesDisplayedLab = new javax.swing.JLabel();
        lab5 = new javax.swing.JLabel();
        movieSearchStatusLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleListMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(titleList);

        searchTextBox.setText("Search...");
        searchTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTextBoxMouseClicked(evt);
            }
        });
        searchTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextBoxActionPerformed(evt);
            }
        });
        searchTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextBoxKeyReleased(evt);
            }
        });

        directoryToSearchTextBox.setText("\\\\\\\\NAS\\\\media\\\\Movies");

        lab1.setText("Directory to search");

        reSearchButton.setText("Reload");
        reSearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reSearchButtonMouseClicked(evt);
            }
        });

        sizeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sizeListMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(sizeList);

        lab4.setText("Total Number Of Movies:");

        numMoviesLab.setText("0");

        lab3.setText("Total Size:");

        totalSizeLab.setText("0MB");

        lab2.setText("Number Of Movies Displayed:");

        numMoviesDisplayedLab.setText("0");

        lab5.setText("Status:");

        movieSearchStatusLab.setText("Done");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(directoryToSearchTextBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchTextBox)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reSearchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lab5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(movieSearchStatusLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(searchingProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lab1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lab2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numMoviesDisplayedLab, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lab4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numMoviesLab, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lab3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalSizeLab)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(directoryToSearchTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reSearchButton)
                            .addComponent(lab5)
                            .addComponent(movieSearchStatusLab))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchingProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 460, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab4)
                    .addComponent(numMoviesLab)
                    .addComponent(lab3)
                    .addComponent(lab2)
                    .addComponent(numMoviesDisplayedLab)
                    .addComponent(totalSizeLab))
                .addContainerGap())
        );

        searchTextBox.getAccessibleContext().setAccessibleName("search_field");
        lab1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextBoxActionPerformed
        searchTextBox.setText("");
    }//GEN-LAST:event_searchTextBoxActionPerformed

    private void reSearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reSearchButtonMouseClicked
        new Thread() {
            public void run() {
                movieSearchStatusLab.setText("Scanning");
                FileList files = new FileList();
                String directory = getImportDirectory();
                files.importFolder(Paths.get(directory));
                movieSearchStatusLab.setText("Writing");
                FileInOut.WriteFileList(files);
                movieSearchStatusLab.setText("Updating Index");
                Search.updateIndex();
                movieSearchStatusLab.setText("Done");
            }
        }.start();
        
    }//GEN-LAST:event_reSearchButtonMouseClicked

    private void searchTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTextBoxMouseClicked
        searchTextBox.setText("");
    }//GEN-LAST:event_searchTextBoxMouseClicked

    private void titleListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleListMousePressed
        sizeList.setSelectedIndex(titleList.getSelectedIndex());
    }//GEN-LAST:event_titleListMousePressed

    private void sizeListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sizeListMousePressed
        titleList.setSelectedIndex(sizeList.getSelectedIndex());
    }//GEN-LAST:event_sizeListMousePressed

    private void searchTextBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextBoxKeyReleased
        files = Search.searchText(searchTextBox.getText());
        String[] nameList = new String[files.size()];
        String[] sizeIntList = new String[files.size()];

        for (int i = 0; i < files.size(); i++) {
            nameList[i] = files.get(i).getName();
            sizeIntList[i] = String.valueOf(files.get(i).getFileSize()) + " MB";
        }
        titleList.setListData(nameList);
        sizeList.setListData(sizeIntList);
        
        this.setNumMoviesDisplayed(String.valueOf(nameList.length));
    }//GEN-LAST:event_searchTextBoxKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField directoryToSearchTextBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab4;
    private javax.swing.JLabel lab5;
    private javax.swing.JLabel movieSearchStatusLab;
    private javax.swing.JLabel numMoviesDisplayedLab;
    private javax.swing.JLabel numMoviesLab;
    private javax.swing.JButton reSearchButton;
    private javax.swing.JTextField searchTextBox;
    private javax.swing.JProgressBar searchingProgressBar;
    private javax.swing.JList sizeList;
    private javax.swing.JList titleList;
    private javax.swing.JLabel totalSizeLab;
    // End of variables declaration//GEN-END:variables
    private ArrayList<FileListEntry> files;
    
    private String getImportDirectory(){
        String temp = directoryToSearchTextBox.getText();
        temp.replace("//", "////");
        
        return temp;
    }

    public void setProgressMax(int max) {
        searchingProgressBar.setMaximum(max);
    }

    public void setProgressMin(int min) {
        searchingProgressBar.setMinimum(min);
    }

    public void setProgressCurrent(int current) {
        searchingProgressBar.setValue(current);
    }

    public void setNumMoviesDisplayed(String newText) {
        numMoviesDisplayedLab.setText(newText);
    }
    public void setNumMovies(String newText) {
        numMoviesLab.setText(newText);
    }
    public void setMovieSearchStatus(String newText) {
        movieSearchStatusLab.setText(newText);
    }
    
    public void setTotalSize(long newNum){
        totalSizeLab.setText(String.valueOf(newNum/Long.parseLong("1099511627776"))
                + "GB");
    }
    
}
